### ISSUE TITLE
Добавление плеера vkplay.live

### ISSUE THREAD

**Issue by grincha09** [honeykingdom/honeykingdom.github.io#4]
### предложение
добавить в доступные форматы каналов сервис vkplay.live

**Comment by DmitryScaletta** [comment]
Добавлено. Спасибо за предложение.
Плеер vkplay встраивается нормально, но чат не встраивается почему-то: `vkplay.live refused to connect.`

Пример:
https://honeykingdom.github.io/?player=vkplay@guitman&chats=guit88man

**Comment by grincha09** [comment]
Супер!
